{"ec13d80f885b4476daf9a13d8e9776be":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"ade1eb2e1a45cf89","status":"passed","time":{"start":1655916757265,"stop":1655916760947,"duration":3682}}]},"670ba3cfeed8a1eae55bab650dfb2951":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"d73ece1aa5c3d2f6","status":"passed","time":{"start":1655916735650,"stop":1655916743499,"duration":7849}}]},"7ea79e93675ccd16049624abeb3d9bec":{"statistic":{"failed":0,"broken":0,"skipped":1,"passed":0,"unknown":0,"total":1},"items":[{"uid":"35432e35d4bf4839","status":"skipped","statusDetails":"XFAIL A dropped test going into x fail, to fix it, you need to change the locator to the correct one\n\nAssertionError: Dropped test going into x fail","time":{"start":1655916771442,"stop":1655916774134,"duration":2692}}]}}